# -*- coding: utf-8 -*-
"""BMI CALCULATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIJe2jdKRn5QooMRSDhMuh2soLm_zmQk
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns

#create BMI calculator
# BMI Calculator in Google Colab

# Function to calculate BMI
def calculate_bmi(weight_kg, height_cm):
    height_m = height_cm / 100
    bmi = weight_kg / (height_m ** 2)
    return round(bmi, 2)

# Function to interpret BMI
def interpret_bmi(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 25:
        return "Normal weight"
    elif 25 <= bmi < 30:
        return "Overweight"
    else:
        return "Obese"

# Input from user
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in cm: "))

# Calculate BMI
bmi = calculate_bmi(weight, height)
category = interpret_bmi(bmi)

# Output
print(f"\nYour BMI is: {bmi}")
print(f"You are classified as: {category}")

# Google Colab-compatible Streamlit BMI Calculator (save as app.py or run in Colab with localtunnel)

import streamlit as st

# App Title
st.title('Welcome to BMI Calculator')

# Weight input
weight = st.number_input("Enter your weight (in kgs)", min_value=1.0, step=0.5)

# Height format selection
status = st.radio('Select your height format:', ('cms', 'meters', 'feet'))

# Height input and BMI calculation
bmi = None
if status == 'cms':
    height = st.number_input('Height (cm)', min_value=1.0, step=1.0)
    if height:
        bmi = weight / ((height / 100) ** 2)

elif status == 'meters':
    height = st.number_input('Height (m)', min_value=0.1, step=0.01)
    if height:
        bmi = weight / (height ** 2)

else:  # feet
    height = st.number_input('Height (feet)', min_value=1.0, step=0.5)
    if height:
        bmi = weight / ((height / 3.28) ** 2)

# Calculate button
if st.button('Calculate BMI'):
    if bmi:
        st.success(f"Your BMI Index is {bmi:.2f}.")

        # BMI Interpretation
        if bmi < 16:
            st.error("You are Extremely Underweight")
        elif bmi < 18.5:
            st.warning("You are Underweight")
        elif bmi < 25:
            st.success("Healthy")
        elif bmi < 30:
            st.warning("Overweight")
        else:
            st.error("Extremely Overweight")
    else:
        st.warning("Please enter valid height and weight values.")