# -*- coding: utf-8 -*-
"""BMI CALCULATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIJe2jdKRn5QooMRSDhMuh2soLm_zmQk
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns

!pip install pyngrok             # Pyngrok is used to expose the local Streamlit app to the web via a public URL
!pip install streamlit-option-menu # Option menu for creating navigation in the app

# Commented out IPython magic to ensure Python compatibility.
# # Writes your code to a python script you can download and upload to your github before delpoying on streamlit cloud.
# %%writefile app.py
# import streamlit as st
# 
# st.title('Welcome to BMI Calculator')
# weight = st.number_input("Enter your weight (in kgs)")
# status = st.radio('Select your height format:', ('cms', 'meters', 'feet'))
# 
# if status == 'cms':
#     height = st.number_input('Centimeters')
#     try:
#         bmi = weight / ((height/100)**2)
#     except:
#         st.text("Enter a valid height value")
# elif status == 'meters':
#     height = st.number_input('Meters')
#     try:
#         bmi = weight / (height ** 2)
#     except:
#         st.text("Enter a valid height value")
# else:
#     height = st.number_input('Feet')
#     try:
#         bmi = weight / (((height/3.28))**2)
#     except:
#         st.text("Enter a valid height value")
# 
# if st.button('Calculate BMI'):
#     st.text(f"Your BMI Index is {bmi}.")
#     if bmi < 16:
#         st.error("You are Extremely Underweight")
#     elif 16 <= bmi < 18.5:
#         st.warning("You are Underweight")
#     elif 18.5 <= bmi < 25:
#         st.success("Healthy")
#     elif 25 <= bmi < 30:
#         st.warning("Overweight")
#     else:
#         st.error("Extremely Overweight")
# 
#

from pyngrok import ngrok

# Terminate existing ngrok processes
!pkill -f ngrok

# Install Ngrok authtoken
!ngrok authtoken 2nsOJTOt5ump7Vz8YhWmAVMCo9U_3FV6cMBUrkg8rGm3RyLQn

# Run Streamlit app
!streamlit run app.py &>/dev/null&

# Create an Ngrok tunnel for port 8501 (Streamlit default port)
public_url = ngrok.connect(8501, "http")

# Print the public URL to access the app
print(public_url)